server {
    listen 80 default_server;
    root /usr/share/nginx/html;

    # Każde żądanie => 503 z markową stroną konserwacji
    location / {
        return 503;
    }

    error_page 503 /index.html;
    location = /index.html {
        internal;
        add_header Retry-After 20 always;
        add_header Cache-Control "no-store" always;
    }
}
